language: java
sudo: false
script: "mvn install:install-file -DgroupId=jta -DartifactId=jta -Dversion=1.0.1 -Dpackaging=jar -Dfile=lib/jta-1_0_1B-classes.jar && mvn verify -B"
cache:
  directories:
    - $HOME/.m2